/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Basic sidebar - will be replaced once API docs are generated
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Cloudflare API',
      link: {
        type: 'generated-index',
        title: 'Cloudflare API',
        description: 'Interactive API Reference for Cloudflare',
        slug: '/',
      },
      items: [{type: 'autogenerated', dirName: '.'}],
    },
  ],
};

module.exports = sidebars;
